### ISSUE TITLE
how to download

### ISSUE THREAD

**Issue by inikishev** [simulot/gogrep#1]
how do i doiwnload this

**Comment by simulot** [comment]
Hi, thanks to your interest into this old project (5 years, time is flying).

There is no download .
You have to get sources and compile it.

**Comment by inikishev** [comment]
> Hi, thanks to your interest into this old project (5 years, time is flying).
> 
> There is no download . You have to get sources and compile it.

I needed search app that could recursively search in zip files for windows, is this project that?

**Comment by simulot** [comment]
Yes, it does it
I have compiled it today.
You can find binaries in master branch.

**Comment by simulot** [comment]
Hi @idkman2021 
I'm please to present a new version of gogrep that runs faster and can be downloaded from release page
